name: Automatic Dependabot Merge

on:
  pull_request:

jobs:
  auto_merge:
    name: "Auto Merge"
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: patch
          github-token: ${{ secrets.GITHUB_TOKEN }}